name: Upload Release Asset

on:
  push:
    tags:
      - 'v*'

jobs:
  linux-build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v3

    - name: Build | Release
      run: make release

    - name: Create | Release Note
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload | Release Note Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/release/vmstat_usage_api
        asset_name: vmstat_usage_api
        asset_content_type: application/octet-stream
